"""initial schema

Revision ID: 9e896fd6a21f
Revises: 
Create Date: 2026-07-26 04:05:50.473264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e896fd6a21f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('params_billion', sa.Float(), nullable=False),
    sa.Column('dtype', sa.String(length=16), nullable=False),
    sa.Column('quantization', sa.String(length=32), nullable=True),
    sa.Column('weight_gb', sa.Float(), nullable=True),
    sa.Column('kv_cache_budget_gb', sa.Float(), nullable=True),
    sa.Column('gpu_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('pending_requests', sa.Integer(), nullable=False),
    sa.Column('total_requests_served', sa.BigInteger(), nullable=False),
    sa.Column('total_errors', sa.BigInteger(), nullable=False),
    sa.Column('state_changed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_model_versions_model_name', 'model_versions', ['model_name'], unique=False)
    op.create_index('ix_model_versions_status', 'model_versions', ['status'], unique=False)
    op.create_table('canary_deployments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('model_v1_id', sa.String(length=64), nullable=False),
    sa.Column('model_v2_id', sa.String(length=64), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('stages', sa.JSON(), nullable=False),
    sa.Column('current_stage_index', sa.Integer(), nullable=False),
    sa.Column('traffic_split', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['model_v1_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['model_v2_id'], ['model_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_canary_deployments_status', 'canary_deployments', ['status'], unique=False)
    op.create_table('canary_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deployment_id', sa.String(length=64), nullable=False),
    sa.Column('stage_index', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('metrics_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['canary_deployments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_canary_events_deployment', 'canary_events', ['deployment_id'], unique=False)
    op.create_table('eval_results',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('deployment_id', sa.String(length=64), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=True),
    sa.Column('score_v1_mean', sa.Float(), nullable=True),
    sa.Column('score_v2_mean', sa.Float(), nullable=True),
    sa.Column('t_statistic', sa.Float(), nullable=True),
    sa.Column('p_value', sa.Float(), nullable=True),
    sa.Column('significant', sa.Boolean(), nullable=True),
    sa.Column('effect_size', sa.Float(), nullable=True),
    sa.Column('dimension_scores', sa.JSON(), nullable=True),
    sa.Column('recommendation', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['canary_deployments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_eval_results_deployment', 'eval_results', ['deployment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_eval_results_deployment', table_name='eval_results')
    op.drop_table('eval_results')
    op.drop_index('ix_canary_events_deployment', table_name='canary_events')
    op.drop_table('canary_events')
    op.drop_index('ix_canary_deployments_status', table_name='canary_deployments')
    op.drop_table('canary_deployments')
    op.drop_index('ix_model_versions_status', table_name='model_versions')
    op.drop_index('ix_model_versions_model_name', table_name='model_versions')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
